# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: keyservers.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='keyservers.proto',
  package='models',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x10keyservers.proto\x12\x06models\"\x1a\n\nKeyservers\x12\x0c\n\x04urls\x18\x01 \x03(\tb\x06proto3')
)




_KEYSERVERS = _descriptor.Descriptor(
  name='Keyservers',
  full_name='models.Keyservers',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='urls', full_name='models.Keyservers.urls', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=54,
)

DESCRIPTOR.message_types_by_name['Keyservers'] = _KEYSERVERS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Keyservers = _reflection.GeneratedProtocolMessageType('Keyservers', (_message.Message,), dict(
  DESCRIPTOR = _KEYSERVERS,
  __module__ = 'keyservers_pb2'
  # @@protoc_insertion_point(class_scope:models.Keyservers)
  ))
_sym_db.RegisterMessage(Keyservers)


# @@protoc_insertion_point(module_scope)
