# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: messaging.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='messaging.proto',
  package='bchmessages',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0fmessaging.proto\x12\x0b\x62\x63hmessages\"%\n\x06Header\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\"O\n\x05\x45ntry\x12\x0c\n\x04kind\x18\x01 \x01(\t\x12$\n\x07headers\x18\x02 \x03(\x0b\x32\x13.bchmessages.Header\x12\x12\n\nentry_data\x18\x03 \x01(\x0c\".\n\x07\x45ntries\x12#\n\x07\x65ntries\x18\x01 \x03(\x0b\x32\x12.bchmessages.Entry\"\xbd\x01\n\x07Payload\x12\x11\n\ttimestamp\x18\x01 \x01(\x03\x12\x13\n\x0b\x64\x65stination\x18\x02 \x01(\x0c\x12\x35\n\x06scheme\x18\x03 \x01(\x0e\x32%.bchmessages.Payload.EncryptionScheme\x12\x13\n\x0bsecret_seed\x18\x04 \x01(\x0c\x12\x0f\n\x07\x65ntries\x18\x05 \x01(\x0c\"-\n\x10\x45ncryptionScheme\x12\x08\n\x04None\x10\x00\x12\x0f\n\x0b\x45phemeralDH\x10\x01\"\x9d\x02\n\x07Message\x12\x32\n\nstamp_type\x18\x01 \x01(\x0e\x32\x1e.bchmessages.Message.StampType\x12\x13\n\x0bstamp_tx_id\x18\x02 \x01(\x0c\x12\x16\n\x0esender_pub_key\x18\x03 \x01(\x0c\x12\x34\n\x06scheme\x18\x04 \x01(\x0e\x32$.bchmessages.Message.SignatureScheme\x12\x11\n\tsignature\x18\x05 \x01(\x0c\x12\x0f\n\x07payload\x18\x06 \x01(\x0c\",\n\tStampType\x12\x08\n\x04None\x10\x00\x12\x15\n\x11MessageCommitment\x10\x01\")\n\x0fSignatureScheme\x12\x0b\n\x07SCHNORR\x10\x00\x12\t\n\x05\x45\x43\x44SA\x10\x01\x62\x06proto3')
)



_PAYLOAD_ENCRYPTIONSCHEME = _descriptor.EnumDescriptor(
  name='EncryptionScheme',
  full_name='bchmessages.Payload.EncryptionScheme',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='None', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='EphemeralDH', index=1, number=1,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=345,
  serialized_end=390,
)
_sym_db.RegisterEnumDescriptor(_PAYLOAD_ENCRYPTIONSCHEME)

_MESSAGE_STAMPTYPE = _descriptor.EnumDescriptor(
  name='StampType',
  full_name='bchmessages.Message.StampType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='None', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MessageCommitment', index=1, number=1,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=591,
  serialized_end=635,
)
_sym_db.RegisterEnumDescriptor(_MESSAGE_STAMPTYPE)

_MESSAGE_SIGNATURESCHEME = _descriptor.EnumDescriptor(
  name='SignatureScheme',
  full_name='bchmessages.Message.SignatureScheme',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='SCHNORR', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ECDSA', index=1, number=1,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=637,
  serialized_end=678,
)
_sym_db.RegisterEnumDescriptor(_MESSAGE_SIGNATURESCHEME)


_HEADER = _descriptor.Descriptor(
  name='Header',
  full_name='bchmessages.Header',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='bchmessages.Header.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='bchmessages.Header.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=32,
  serialized_end=69,
)


_ENTRY = _descriptor.Descriptor(
  name='Entry',
  full_name='bchmessages.Entry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='kind', full_name='bchmessages.Entry.kind', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='headers', full_name='bchmessages.Entry.headers', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='entry_data', full_name='bchmessages.Entry.entry_data', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=71,
  serialized_end=150,
)


_ENTRIES = _descriptor.Descriptor(
  name='Entries',
  full_name='bchmessages.Entries',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='entries', full_name='bchmessages.Entries.entries', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=152,
  serialized_end=198,
)


_PAYLOAD = _descriptor.Descriptor(
  name='Payload',
  full_name='bchmessages.Payload',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='bchmessages.Payload.timestamp', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='destination', full_name='bchmessages.Payload.destination', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='scheme', full_name='bchmessages.Payload.scheme', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='secret_seed', full_name='bchmessages.Payload.secret_seed', index=3,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='entries', full_name='bchmessages.Payload.entries', index=4,
      number=5, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _PAYLOAD_ENCRYPTIONSCHEME,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=201,
  serialized_end=390,
)


_MESSAGE = _descriptor.Descriptor(
  name='Message',
  full_name='bchmessages.Message',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='stamp_type', full_name='bchmessages.Message.stamp_type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='stamp_tx_id', full_name='bchmessages.Message.stamp_tx_id', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sender_pub_key', full_name='bchmessages.Message.sender_pub_key', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='scheme', full_name='bchmessages.Message.scheme', index=3,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='signature', full_name='bchmessages.Message.signature', index=4,
      number=5, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='payload', full_name='bchmessages.Message.payload', index=5,
      number=6, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _MESSAGE_STAMPTYPE,
    _MESSAGE_SIGNATURESCHEME,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=393,
  serialized_end=678,
)

_ENTRY.fields_by_name['headers'].message_type = _HEADER
_ENTRIES.fields_by_name['entries'].message_type = _ENTRY
_PAYLOAD.fields_by_name['scheme'].enum_type = _PAYLOAD_ENCRYPTIONSCHEME
_PAYLOAD_ENCRYPTIONSCHEME.containing_type = _PAYLOAD
_MESSAGE.fields_by_name['stamp_type'].enum_type = _MESSAGE_STAMPTYPE
_MESSAGE.fields_by_name['scheme'].enum_type = _MESSAGE_SIGNATURESCHEME
_MESSAGE_STAMPTYPE.containing_type = _MESSAGE
_MESSAGE_SIGNATURESCHEME.containing_type = _MESSAGE
DESCRIPTOR.message_types_by_name['Header'] = _HEADER
DESCRIPTOR.message_types_by_name['Entry'] = _ENTRY
DESCRIPTOR.message_types_by_name['Entries'] = _ENTRIES
DESCRIPTOR.message_types_by_name['Payload'] = _PAYLOAD
DESCRIPTOR.message_types_by_name['Message'] = _MESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Header = _reflection.GeneratedProtocolMessageType('Header', (_message.Message,), dict(
  DESCRIPTOR = _HEADER,
  __module__ = 'messaging_pb2'
  # @@protoc_insertion_point(class_scope:bchmessages.Header)
  ))
_sym_db.RegisterMessage(Header)

Entry = _reflection.GeneratedProtocolMessageType('Entry', (_message.Message,), dict(
  DESCRIPTOR = _ENTRY,
  __module__ = 'messaging_pb2'
  # @@protoc_insertion_point(class_scope:bchmessages.Entry)
  ))
_sym_db.RegisterMessage(Entry)

Entries = _reflection.GeneratedProtocolMessageType('Entries', (_message.Message,), dict(
  DESCRIPTOR = _ENTRIES,
  __module__ = 'messaging_pb2'
  # @@protoc_insertion_point(class_scope:bchmessages.Entries)
  ))
_sym_db.RegisterMessage(Entries)

Payload = _reflection.GeneratedProtocolMessageType('Payload', (_message.Message,), dict(
  DESCRIPTOR = _PAYLOAD,
  __module__ = 'messaging_pb2'
  # @@protoc_insertion_point(class_scope:bchmessages.Payload)
  ))
_sym_db.RegisterMessage(Payload)

Message = _reflection.GeneratedProtocolMessageType('Message', (_message.Message,), dict(
  DESCRIPTOR = _MESSAGE,
  __module__ = 'messaging_pb2'
  # @@protoc_insertion_point(class_scope:bchmessages.Message)
  ))
_sym_db.RegisterMessage(Message)


# @@protoc_insertion_point(module_scope)
